[program:rtpproxy]
command=/usr/local/bin/rtpproxy -l 0.0.0.0 -s udp:0.0.0.0:7722 -P /var/run/rtpproxy/rtpproxy.pid -D -f -m 5000:60000
user=rtpproxy
autostart=true
autorestart=true
#stderr_logfile=/var/log/rtpproxy.err.log
#stdout_logfile=/var/log/rtpproxy.out.log
stderr_logfile=/home/user/rtpproxy.err.log
stdout_logfile=/home/user/rtpproxy.out.log
