version: '3.8'

services:
  kamailio:
    build:
      context: ./kamailio-v1
      dockerfile: Dockerfile
    ports:
      - "5060:5060/udp"
    depends_on:
      - db
    restart: always
    networks:
      - sipnet
    #networks:
      #kamailio:
        #ipv4_address: 192.168.168.3

  db:
    build:
      context: ./postgresql
      dockerfile: postgres.dockerfile
    environment:
      POSTGRES_PASSWORD: notkamailio
      POSTGRES_DB: kamailio
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
    networks:
      - sipnet
    #networks:
      #kamailio:
        #ipv4_address: 192.168.168.4

  rtpengine:
    build:
      context: ./rtpengine
      dockerfile: rtpengine.dockerfile
    volumes:
      - ./rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf
    networks:
      - sipnet
    #networks:
      #kamailio:
        #ipv4_address: 192.168.168.5


networks:
  sipnet:
    driver: bridge
  kamailio:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.168.0/24
         gateway: 192.168.168.1
